### ISSUE TITLE
Duplicate and unused Docker environment variables

### ISSUE THREAD

**Issue by FraBle** [qnib/plain-zkui#1]
- `ZKUI_ADMIN_PW` is set twice (first to `manager`, later to `admin`)
- `ZKUI_PORT` is set twice to 9090
- `20-config-zkui.sh` does not replace  `ZKUI_USER_PW` in `zkui.conf.orig`

**Comment by ChristianKniep** [comment]
Thanks @FraBle, I'll have a look in a bit.
